# Generated by Django 3.2.7 on 2021-11-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone_number', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Location', models.CharField(max_length=100)),
                ('Lawyer_Qualification', models.CharField(max_length=200)),
                ('specilization', models.CharField(max_length=200)),
            ],
        ),
    ]
