# Generated by Django 3.2.7 on 2021-11-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerSpecilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.IntegerField()),
                ('SpecilizationType', models.CharField(max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('raitings', models.IntegerField(default=0)),
                ('Lawyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawyers.lawyers')),
            ],
        ),
    ]
