# Generated by Django 3.2.7 on 2021-11-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0002_lawyerspecilization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyers',
            name='specilization',
        ),
    ]
