# Generated by Django 3.2.7 on 2022-03-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0003_remove_lawyers_specilization'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyers',
            name='noOfViews',
            field=models.IntegerField(default=0),
        ),
    ]
