# Generated by Django 3.2.7 on 2022-06-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0004_lawyers_noofviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyers',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lawyers',
            name='profileUrl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
